//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCenter2
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Atleti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atleti()
        {
            this.Sedute = new ObservableCollection<Sedute>();
        }
    
        public int AtletaID { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public decimal peso { get; set; }
        public Nullable<System.DateTime> DataDiNascita { get; set; }
        public decimal Altezza { get; set; }
        public byte[] Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Sedute> Sedute { get; set; }
    }
}
