//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCenter2
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Sedute
    {
        public string SedutaID { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan OraInizio { get; set; }
        public System.TimeSpan OraFine { get; set; }
        public string SportID { get; set; }
        public Nullable<int> AtletaID { get; set; }
    
        public virtual Atleti Atleti { get; set; }
        public virtual Sedute Sedute1 { get; set; }
        public virtual Sedute Sedute2 { get; set; }
    }
}
